"""empty message

Revision ID: 061fca2a286c
Revises: 70ade5e79840
Create Date: 2025-03-01 13:22:30.783895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061fca2a286c'
down_revision = '70ade5e79840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_admin', sa.String(length=150), nullable=False))
        batch_op.drop_constraint('admin_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email_admin'])
        batch_op.drop_column('email')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_reservation', sa.String(length=120), nullable=False))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('email_reservation')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('admin_email_key', ['email'])
        batch_op.drop_column('email_admin')

    op.drop_table('order')
    # ### end Alembic commands ###
