"""empty message

Revision ID: 1485c10ed5b9
Revises: 7183a5866e20
Create Date: 2025-03-03 13:08:21.039918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1485c10ed5b9'
down_revision = '7183a5866e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['product_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_order', schema=None) as batch_op:
        batch_op.drop_column('items')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.TEXT(), autoincrement=False, nullable=False))

    op.drop_table('order_item')
    # ### end Alembic commands ###
