"""empty message

Revision ID: 7183a5866e20
Revises: 34fee1e237f6
Create Date: 2025-03-02 22:22:24.830997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7183a5866e20'
down_revision = '34fee1e237f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_order', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
