"""empty message

Revision ID: 960417f978f6
Revises: 836334214baa
Create Date: 2025-03-06 22:34:51.300186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960417f978f6'
down_revision = '836334214baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_order', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
